### ISSUE TITLE
Inventory items are offset by 2 pixels in the x plane when opening bank interface

### ISSUE THREAD

**Issue by ryannathans** [Pazaz/RT4-Client#10]
you can see the inventory move when you enter the bank interface

legacy client in bank
![image](https://user-images.githubusercontent.com/1307375/190997203-1d4d1b19-a5e7-45e3-8ac1-4e6a5792837d.png)

rt4-client in bank
![image](https://user-images.githubusercontent.com/1307375/190997341-f16ff2f5-f11f-465a-8aa0-e34044a3f31d.png)

rt4-client not in bank
![image](https://user-images.githubusercontent.com/1307375/190997393-6d36c128-9b8c-4f17-aace-520bf9b88858.png)

lined up
![bank inv](https://user-images.githubusercontent.com/1307375/190998561-829759f7-0dcf-40e0-8b9d-0dd7d0282cfd.png)

**Comment by Ceikry** [comment]
Looks like the same problem that was causing the equipment interface offset. Which tells me this is an issue with rendering certain item containers that are sent by the server during runtime

**Comment by Pazaz** [comment]
Fixed by now I think. Should confirm before closing

**Comment by ryannathans** [comment]
> Fixed by now I think. Should confirm before closing

looks like the offset is fixed but now it looks like there's a double drop shadow which is removed when the bank opens?

bank closed
![image](https://user-images.githubusercontent.com/1307375/202309687-24e285d3-5805-4d91-88d4-7039e0dfae07.png)


bank opened
![image](https://user-images.githubusercontent.com/1307375/202309735-db6da37d-b656-4f24-a006-874dd4b4bda5.png)

it's especially noticeable on the arrows and air runes
