### ISSUE TITLE
some icons missing from chat box

### ISSUE THREAD

**Issue by ryannathans** [Pazaz/RT4-Client#7]
![image](https://user-images.githubusercontent.com/1307375/179344729-42587e03-1824-418d-8e6a-5c625ca7daf2.png)

Ex is a hcim and the icon was not showing

![image](https://user-images.githubusercontent.com/1307375/179344808-14b58cae-7a69-42c3-8854-50cabd9fdd57.png)

quickchat messages also don't have an icon shown

**Comment by Pazaz** [comment]
Forgot to reply here. This is a server-specific feature (not original to 2009), I think when the client has a plugin system it would be better suited as a chat handler plugin.
