### ISSUE TITLE
Sound not working.

### ISSUE THREAD

**Issue by 6six1** [Pazaz/RT4-Client#9]
errors occur when starting client, terminal also spits them out when attempting to switch audio modes.

pc specs~

cpu; AMD Ryzen 5 3600X

motherboard; msi x570 gaming plus wifi
 
ram; 16gb ddr4

gpu; SAPPHIRE PULSE RX 5600 XT

Operating system; Pop! Os 22.04

![image](https://user-images.githubusercontent.com/112450117/187330166-3f11feaa-60ce-47a4-8208-dd640f1a894d.png)

**Comment by Ceikry** [comment]
Yep, this is known. It's actually a bug with Pop OS (specifically pop)'s configuration of Pipewire, which they introduced in 22.04. I am a Pop user myself and have the same issue. The issue does not occur on other distros that use Pipewire.

**Comment by ryannathans** [comment]
pipewire bug has since been fixed upstream in pipewire repo, @pandaEatsMeth issue can be closed
